/*
 * RCC_Interface.h
 *
 *  Created on: Feb 25, 2025
 *      Author: Ahmed
 */

#ifndef RCC_RCC_INTERFACE_H_
#define RCC_RCC_INTERFACE_H_

#include "RCC_Registers.h"
#include "RCC_Config.h"

/* Marcos for RCC Peripherals */
typedef enum
{
	GPIOA_EN,
	GPIOB_EN,
	GPIOC_EN,
	GPIOD_EN,
	GPIOE_EN,
	GPIOF_EN,
	GPIOG_EN,
	GPIOH_EN,
	GPIOI_EN,
	GPIOJ_EN,
	GPIOK_EN,
	CRCEN_EN = 12,
	BKPSRAMEN_EN = 19,
	CCMDATARAMEN_EN,
	DMA1EN_EN,
	DMA2EN_EN,
	DMA2DEN_EN,
	ETHMACEN_EN = 25,
	ETHMACTXEN_EN,
	ETHMACRXEN_EN,
	ETHMACPTPEN_EN,
	OTGHSEN_EN,
	OTGHSULPIEN_EN,

	// RCC_AHB2ENR. from 31
	DCMIEN_EN,
	CRYPEN_EN = 35,
	HASHEN_EN,
	RNGEN_EN,
	OTGFSEN_EN,

	// RCC_AHB3ENR. from 39
	FSMCEN,

	// RCC_APB1ENR. From 40
	TIM2EN,
	TIM3EN,
	TIM4EN,
	TIM5EN,
	TIM6EN,
	TIM7EN,
	TIM12EN,
	TIM13EN,
	TIM14EN,
	WWDGEN = 51,
	SPI2EN = 54,
	SPI3EN,
	USART2EN = 57,
	USART3EN,
	UART4EN,
	UART5EN,
	I2C1EN,
	I2C2EN,
	I2C3EN,
	CAN1EN = 65,
	CAN2EN,
	PWREN = 68,
	DACEN,

	// RCC_APB2ENR. from 70
	TIM1EN,
	TIM8EN,
	USART1EN = 74,
	USART6EN,
	ADC1EN = 78,
	ADC2EN,
	ADC3EN,
	SDIOEN,
	SPI1EN,
	SYSCFGEN = 84,
	TIM9EN = 86,
	TIM10EN,
	TIM11EN,

	// RCC_AHB1LPENR. from 89
	GPIOALPEN,
	GPIOBLPEN,
	GPIODLPEN,
	GPIOELPEN,
	GPIOFLPEN,
	GPIOGLPEN,
	GPIOHLPEN,
	GPIOILPEN,
	GPIOJLPEN,
	GPIOKLPEN,
	CRCLPEN = 100,
	FLITFLPEN = 102,
	SRAM1LPEN,
	SRAM2LPEN,
	BKPSRAMLPEN,
	DMA1LPEN = 108,
	DMA2LPEN,
	ETHMACLPEN = 112,
	ETHMACTXLPEN,
	ETHMACRXLPEN,
	ETHMACPTPLPEN,
	OTGHSLPEN,
	OTGHSULPILPEN,

	// RCC_AHB2LPENR. from 118
	DCMILPEN,
	CRYPLPEN = 122,
	HASHLPEN,
	RNGLPEN,
	OTGFSLPEN,

	// RCC_AHB3LPENR. from 126
	FSMCLPEN,

	// RCC_APB1LPENR. from 127
	TIM2LPEN,
	TIM3LPEN = 128,
	TIM4LPEN,
	TIM5LPEN,
	TIM6LPEN,
	TIM7LPEN,
	TIM12LPEN,
	TIM13LPEN,
	TIM14LPEN,
	WWDGLPEN = 138,
	SPI2LPEN = 141,
	SPI3LPEN,
	USART2LPEN,
	USART3LPEN,
	UART4LPEN,
	UART5LPEN,
	I2C1LPEN,
	I2C2LPEN,
	I2C3LPEN,
	CAN1LPEN = 151,
	CAN2LPEN,
	PWRLPEN = 154,
	DACLPEN,

	// RCC_APB2LPENR. from 156
	 TIM1LPEN,
	 TIM8LPEN,
	 USART1LPEN = 160,
	 USART6LPEN,
	 ADC1LPEN = 164,
	 ADC2LPEN,
	 ADC3LPEN,
	 SDIOLPEN,
	 SPI1LPEN,
	 SYSCFGLPEN = 170,
	 TIM9LPEN = 172,
	 TIM10LPEN,
	 TIM11LPEN
}RCC_Preipherals;


void RCC_init(void); // Refer to the RCC_Config file to use this function properly. You need to choose "System Clock" and "Prescaler" for the AHB, APB1 and PPB2 Buses //
void RCC_External_Clock_MCO1(void);
void RCC_External_Clock_MCO2(void);
void RCC_Peri_Enable(RCC_Preipherals P);
void RCC_Peri_Disable(RCC_Preipherals P);





#endif /* RCC_RCC_INTERFACE_H_ */
